OPSEXP-2445 Prepare for 7.1.0-M.1 release
Alfresco/acs-deployment pull request #1073
Opened 2024-01-18 14:10 UTC by gionn

Ref: OPSEXP-2445

2024-01-18 16:39 UTC, alxgomz requested changes
I’m wondering if ATS, ASE & ADW bump are not early Eridanus work vs Draco stuff.
There was no release for these components in draco

2024-01-18 16:39 UTC, alxgomz commented on README.md
> +| [7.1.0-M.1][7.1.0-M.1] | 23.1.1     | 7.4.1.3 | 7.3.1.2 | 7.2.1.13 | 7.1.1.10 | 7.0.1.10 | 23.1.0    |
```suggestion
| [7.1.0-M.1][7.1.0-M.1] | 23.2.0-M1  | 7.4.1.3 | 7.3.1.2 | 7.2.1.13 | 7.1.1.10 | 7.0.1.10 | 23.1.0    |
```

2024-01-18 16:39 UTC, alxgomz commented on helm/alfresco-content-services/Chart.yaml
>  appVersion: 23.1.1
```suggestion
appVersion: 23.2.0-M1
```

2024-01-19 08:38 UTC, gionn commented on docker-compose/docker-compose.yml
> +    image: quay.io/alfresco/alfresco-control-center:4.3.0
```suggestion
    image: quay.io/alfresco/alfresco-control-center:8.3.0
```

2024-01-19 14:09 UTC, alxgomz requested changes

2024-01-19 14:09 UTC, alxgomz commented on test/enterprise-integration-test-values.yaml
> +    enabled: true
to remove

2024-01-19 14:42 UTC, alxgomz submitted a review, later dismissed

2024-01-19 17:32 UTC, alxgomz approved these changes

2024-01-22 08:19 UTC, merged