OPSEXP-2449 Deploy search enterprise by default
Alfresco/acs-deployment pull request #1095
Opened 2024-02-14 09:53 UTC by gionn

* Previous versions and community still deploy solr
* Validate repository search flavor to avoid inconsinstencies

Ref: OPSEXP-2449

2024-02-16 16:13 UTC, alxgomz requested changes

2024-02-16 16:13 UTC, alxgomz commented on helm/alfresco-content-services/templates/_helpers-search.tpl
IF I want to dpeloy acs with solr & ES and use solr i nthe first place (e.g. I'm preparing a migration scenario) then that is not possible anymore with this change I think.
Are you trying to fix a bug or just had more consistency (less flexibility)?

2024-02-16 16:13 UTC, alxgomz commented on docs/helm/upgrades.md
> +* Search Enterprise is now the default search engine when installing Enterprise
Can you add a small doc on how to configure an external ES index and link to it from here?

2024-02-16 16:30 UTC, gionn commented on helm/alfresco-content-services/templates/_helpers-search.tpl
if that's a scenario we want to support then I can relax the check when both search and search enterprise are enabled.

I want to avoid the situation where repository is configured for a search backend which is not the currently enabled based on `.enabled` values, which is causing a failure only at deployment stage where repository container cannot be created due to missing keys in the configmap.

2024-02-20 10:57 UTC, pmacius approved these changes

2024-02-20 14:01 UTC, alxgomz approved these changes

2024-02-21 14:15 UTC, merged