OPSEXP-2462 Create new values file for pre-released versions and make default values file only for released images
Alfresco/acs-deployment pull request #1104
Opened 2024-02-27 16:55 UTC by pmacius

!Ref OPSEXP-2462

2024-02-28 14:17 UTC, pmacius commented
Please take a look if this looks all right, then I will test pipeline bumping versions :)

2024-02-28 14:29 UTC, alxgomz requested changes
version based values & docker files should not contain pre-release versions. Was the updatecli pipelines hanged on purpose while we wait for releases to happen?

2024-02-28 14:41 UTC, alxgomz commented on docker-compose/pre-release-docker-compose.yml
> +    image: quay.io/alfresco/alfresco-content-repository:23.2.0-M1
Argh sorry my bad! I missed the file was renamed

2024-02-28 14:54 UTC, pmacius commented
> Was the updatecli pipelines hanged on purpose while we wait for releases to happen?
Yes, I think that it will cause less trouble if we stick to those tags for now and wait for new release.

2024-02-28 15:17 UTC, gionn requested changes

2024-02-28 15:17 UTC, gionn commented on helm/alfresco-content-services/values.yaml
would expect tag changes in this file (from -A to GA versions)

2024-02-28 15:52 UTC, pmacius commented
https://github.com/Alfresco/acs-deployment/actions/runs/8082979440/job/22084993920

2024-02-29 11:42 UTC, gionn requested changes

2024-02-29 11:42 UTC, gionn commented on updatecli-matrix-targets.yaml
> +      helm_update_appVersion: &helm_update_appVersion false
remove it, default is false

put this block to `current` (I can explain better why this is needed in private xD)
```
      # keep the unused anchor to detect multiple usages when copying blocks for new versions
      helm_update_appVersion: &helm_update_appVersion true
```

2024-02-29 14:22 UTC, gionn approved these changes

2024-03-01 11:21 UTC, alxgomz approved these changes

2024-03-01 11:22 UTC, merged