Add ability to configure TLS section
Alfresco/acs-deployment pull request #541
Opened 2021-04-06 17:02 UTC by bartjkdp

2021-04-06 17:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/acs-deployment?pullRequest=541) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/acs-deployment?pullRequest=541) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/acs-deployment?pullRequest=541) it.</sub>

2021-04-07 09:28 UTC, gavincornwell requested changes
The changes look good to me, however, the 6.1.N_values.yaml and 6.2.N_values.yaml should also have the same changes applied to them for consistency.

2021-04-07 13:24 UTC, bartjkdp commented
Thanks a lot for the review @gavincornwell. I made the required changes to these files.

2021-04-08 07:55 UTC, gavincornwell commented
Thank you @bartjkdp, I'm going to try and trigger our automated build against your branch before merging. I will let you know how it goes.

2021-04-08 10:37 UTC, nilsSure approved these changes
Looks ok

2021-04-08 10:49 UTC, sergiuv2020 approved these changes

2021-04-08 11:21 UTC, gavincornwell approved these changes
The build has completed successfully so I'll go ahead and merge. 

Thank you for your contribution.

2021-04-08 11:23 UTC, gavincornwell commented
@bartjkdp After all that it seems there is now a conflict due to a recent change on master, would you mind pulling master into your branch and addressing the conflict?

2021-04-08 12:01 UTC, bartjkdp commented
@gavincornwell sure, just rebased on the latest version master branch.

2021-04-08 12:32 UTC, merged