add tagging 'latest' skipci
Alfresco/acs-deployment pull request #559
Opened 2021-05-21 14:31 UTC by alxgomz

add the 'latest' tag to pushed released (follow version tag)

2021-05-21 14:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/acs-deployment?pullRequest=559) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/acs-deployment?pullRequest=559) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/acs-deployment?pullRequest=559) it.</sub>

2021-05-28 15:41 UTC, alxgomz commented on .travis.yml
> +          git tag -a -m "current lastest -> $GIT_TAG" -f latest ${GIT_TAG}^{}
OPSEXP-907 really mentions "latest" and not "lastest".
Also according to the link below, latest is what we want (... I think):
https://www.askdifference.com/lastest-vs-latest/

2021-06-03 09:40 UTC, mteodori requested changes

2021-06-03 09:40 UTC, mteodori commented on .travis.yml
> +          git tag -a -m "current lastest -> $GIT_TAG" -f latest ${GIT_TAG}^{}
no lastest rather than latest is in the commit message and should be amended to match :)

2021-06-03 12:08 UTC, alxgomz commented on .travis.yml
> +          git tag -a -m "current lastest -> $GIT_TAG" -f latest ${GIT_TAG}^{}
Had to read it 3 times before spotting it

2021-06-28 10:24 UTC, alxgomz commented on .travis.yml
> +          for ref in ':refs/tags/latest' 'latest'
Well spotted, changed to the right repo.

2021-06-28 10:24 UTC, mteodori approved these changes

2021-06-28 10:28 UTC, merged