[ACS-2158] Replaced transformer for tranforming microsoft-specific ex…
Alfresco/acs-deployment pull request #629
Opened 2021-12-07 16:56 UTC by kcichonczyk

Replaced transformer for tranforming microsoft-specific extensions to txt from LibreOffice to TikaAuto.

2021-12-07 16:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/acs-deployment?pullRequest=629) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/acs-deployment?pullRequest=629) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/acs-deployment?pullRequest=629) it.</sub>

2021-12-08 08:53 UTC, alandavis requested changes

2021-12-08 08:53 UTC, alandavis commented on helm/alfresco-content-services/templates/config-transformer-routes.yaml
>              {"sourceMediaType": "application/vnd.ms-powerpoint",                                              "maxSourceSizeBytes": -1, "targetMediaType": "application/vnd.alfresco.ai.features.v1+jso
I think you need to remove the ms-powerpoint line as that is now covered by the new transform.

2021-12-08 09:14 UTC, alandavis requested changes

2021-12-08 09:14 UTC, alandavis commented on helm/alfresco-content-services/templates/config-transformer-routes.yaml
> +            {"transformerName": "TikaAuto", "targetMediaType": "text/plain"},
Is this the correct transformer?

2021-12-08 11:06 UTC, kcichonczyk commented on helm/alfresco-content-services/templates/config-transformer-routes.yaml
> +            {"transformerName": "TikaAuto", "targetMediaType": "text/plain"},
replaced with OutlookMsg

2021-12-08 11:22 UTC, pzhyland approved these changes
LGTM

2021-12-08 11:40 UTC, alandavis reviewed
LGTM - please wait for a green build before merging

2021-12-08 11:46 UTC, alandavis requested changes
When we have a new transformer 'A' releases, these will need to be set in this PR before we merge.

2021-12-10 15:15 UTC, alandavis approved these changes

2021-12-13 19:07 UTC, merged