ACS 7.2.0 and 7.1.1 (start of code freeze for ACS 7.2.0-M2 and 7.1.1 GA)
Alfresco/acs-deployment pull request #641
Opened 2022-01-19 11:32 UTC by alandavis

* Repo: 7.2.0-A20 and 7.1.1-A5
* Share: 7.2.0-A20 and 7.1.1-A5
* T-Router: 1.5.0-A3
* T-Engine: 2.5.5-A3
* SFS: 0.16.1-A1

2022-01-19 11:49 UTC, alxgomz requested changes

2022-01-19 11:49 UTC, alxgomz commented on README.md
> +| 5.2.0-?           | 7.2.0-A20 | 7.1.1-A5 | 7.0.1 | 6.2.2 | 6.1.1 | 7.2.0-M1  |
Isn't it M2?

2022-01-19 11:57 UTC, alxgomz commented
You'll also need to update the Chart.yml before merging otherwise you'll endup overwriting the 5.2.0-M1 incubator release

2022-01-20 17:06 UTC, alxgomz requested changes
Make sure to bump chart version in `acs-deployment/helm/alfresco-content-services/Chart.yaml` otherwise you'll endup overwriting 5.2.0-M1 in incubator

2022-01-21 05:42 UTC, alandavis commented
Changed the version as requested https://github.com/Alfresco/acs-deployment/pull/641#pullrequestreview-858551059 but why am I having to do this? The devops team should have released the 5.2.0-M1 from the incubator to stable weeks ago at the end of the last train's code freeze. I note that the sync-service has already been updated on master for the current code freeze, so 5.2.0-M1 already has been overwritten. I will leave the devops team to fix that.

2022-01-25 13:35 UTC, alxgomz approved these changes
LGTM

2022-01-25 14:41 UTC, closed without merging