OPSEXP-1447: split alfresco-common into a library chart of its own
Alfresco/acs-deployment pull request #773
Opened 2022-09-20 12:04 UTC by alxgomz

Ref: OPSEXP-1447

This PR only takes care of creating that new charts and fixing the actual issue with conflicting dependencies.
Further chagnes are needed to adapt the release build/process

2022-09-26 11:18 UTC, kklassa approved these changes

2022-09-26 11:18 UTC, kklassa commented on helm/alfresco-content-services/Chart.yaml
> +    version: 0.1.0-A417
just a note that after merging https://github.com/Alfresco/alfresco-build-tools/pull/120 the incubator charts by default will be created with the SNAPSHOT suffix, so like `0.1.0-SNAPSHOT`

2022-09-26 11:18 UTC, kklassa commented on .github/workflows/verify.yml
> +          - alfresco-content-service
also, I don't know if you intended it this way but in the current state when the matrix is defined but not referenced the action will publish the same thing twice I think

2022-09-27 13:17 UTC, gionn requested changes

2022-09-27 13:17 UTC, gionn commented on .github/workflows/verify.yml
> -      - pr-*
keep master or it will trigger 2x workflow when branch is not in sync with master

2022-09-27 13:17 UTC, gionn commented on .github/workflows/verify.yml
> +      - uses: hmarr/debug-action@v2.0.1
remove before merge

2022-09-27 13:17 UTC, gionn commented on .github/workflows/verify.yml
> +          - alfresco-content-services
it is fine to do this in parallel?

2022-09-28 08:03 UTC, gionn approved these changes

2022-09-28 10:02 UTC, merged