OPSEXP-1796 Release ACS 7.3
Alfresco/acs-deployment pull request #801
Opened 2022-11-04 09:54 UTC by gionn

OPSEXP-1796

2022-11-04 09:56 UTC, gionn commented on helm/alfresco-content-services/7.2.N_values.yaml
> +      tag: 3.7.2
reverted because https://docs.alfresco.com/content-services/latest/support/ (7.2) doesn't list sync 3.8 but list sync 3.7

2022-11-14 09:19 UTC, alxgomz requested changes
ADW support for ACS 7.2 has now been updated to 3.0. Please update

2022-11-14 13:10 UTC, alxgomz reviewed
Why is there a `7.3.N-docker-compose.yml` & `7.3.N_values.yaml` when those versions should actually be dealt with within the default `docker-compose.yml` & `values.yaml` files?

2022-11-14 13:49 UTC, gionn commented
> Why is there a `7.3.N-docker-compose.yml` & `7.3.N_values.yaml` when those versions should actually be dealt with within the default `docker-compose.yml` & `values.yaml` files?

from the [README.md](https://github.com/Alfresco/acs-deployment#versioning)

> The master branch of this repository now contains the artifacts required to deploy both the the latest work-in-progress development version and previous stable versions of ACS.

2022-11-15 17:38 UTC, alxgomz requested changes
please remove the 7.3.N docker compose file too

2022-11-16 10:47 UTC, alxgomz approved these changes

2022-11-16 13:15 UTC, merged