OPSEXP-1651 Use existing secret to configure ACS postgres credentials
Alfresco/acs-deployment pull request #840
Opened 2023-01-05 09:56 UTC by gionn

Ref: OPSEXP-1651

2023-01-08 21:38 UTC, alxgomz reviewed
again, we could use `envFrom` to inject the whole secret

2023-01-09 09:13 UTC, gionn commented
> again, we could use `envFrom` to inject the whole secret

can't use `envFrom` because secret contain keys like `DATABASE_PASSWORD` while the container requires `SPRING_DATASOURCE_PASSWORD`

2023-01-10 18:05 UTC, alxgomz requested changes

2023-01-10 18:05 UTC, alxgomz commented on helm/alfresco-content-services/tests/secret-database_test.yaml
> +          value: YWxmcmVzY28=
dup?

2023-01-10 18:05 UTC, alxgomz commented on helm/alfresco-content-services/tests/secret-database_test.yaml
> +          value: bXljdXN0b21hZG1pbg==
dup?

2023-01-11 08:21 UTC, gionn commented on helm/alfresco-content-services/tests/secret-database_test.yaml
> +          value: YWxmcmVzY28=
yes 🤦🏻

2023-01-11 19:43 UTC, alxgomz approved these changes

2023-01-12 09:58 UTC, alxgomz approved these changes

2023-01-12 09:58 UTC, merged