OPSEXP-1826 Have a dedicated value to toggle outbound email configuration
Alfresco/acs-deployment pull request #853
Opened 2023-01-17 13:37 UTC by gionn

2023-01-17 13:37 UTC, gionn commented on helm/alfresco-content-services/templates/deployment-repository.yaml
> -              name: {{ template "content-services.shortname" . }}-mail-password
😅

2023-01-17 13:38 UTC, gionn commented on helm/alfresco-content-services/templates/deployment-repository.yaml
>                name: {{ default (printf "%s-mail-password" (include "content-services.shortname" .)) .Values.mail.existingSecretName }}
😅

2023-01-17 19:13 UTC, alxgomz requested changes

2023-01-18 15:36 UTC, alxgomz approved these changes
please review suggestion otherwsie that's GTM

2023-01-18 15:36 UTC, alxgomz commented on helm/alfresco-content-services/templates/config-repository.yaml
> +      -Dmail.username={{ .Values.mail.username }}
```suggestion
      {{- printf('-Dmail.username=%s' .Values.mail.username) | default "" }}
```

As we can't really put a default inthe `values.yaml` file

2023-01-18 15:36 UTC, alxgomz commented on helm/alfresco-content-services/templates/config-repository.yaml
> +      -Dmail.from.default={{ .Values.mail.from.default }}
```suggestion
      {{- printf('-Dmail.from.default=%s' .Values.mail.from.default) | default "" }}
```

2023-01-19 15:23 UTC, gionn commented
> please review suggestion otherwsie that's GTM

I understand that always explicitly providing a system prop via `-D` could actually change default behavior by overriding a possible default at application level, but I would prefer to not increase complexity if we don't have really an issue on a particular property.

2023-01-19 15:23 UTC, merged