OPSEXP-139 Document custom images overrides
Alfresco/acs-deployment pull request #855
Opened 2023-01-18 14:15 UTC by gionn

OPSEXP-139

2023-01-18 15:03 UTC, alxgomz requested changes
Can you please add:
* a mention that custom images should ALWAYS be used as we provide some just for convenient but do not commit to publish security update for softwares or lib that are out of our control
* Add an example of using a custom image from an authenticated registry.

2023-01-18 16:47 UTC, vprovaggi reviewed
my opinion on making the documentation a bit easier to read

2023-01-18 16:47 UTC, vprovaggi commented on docs/helm/README.md
> +## What to expect from the ACS Helm charts
```suggestion
## Overview
```

2023-01-18 16:47 UTC, vprovaggi commented on docs/helm/README.md
> +your organisation.
```suggestion
Alfresco provides tested Helm charts as a "template" to accelerate deployment and configuration for customers
who wants to take advantage of Kubernetes orchestration capabilities. Please remember that as stated in our [support policies](https://docs.alfresco.com/support/latest/policies/deployment/), similarly to other deployment artifacts, they are not meant to be used 'as-is' in production.

Our goal is to save you time and effort deploying Alfresco Content Services for
your organization. 
```

2023-01-18 16:47 UTC, vprovaggi commented on docs/helm/README.md
> +your database.
```suggestion
You typically want
to remove the PostgreSQL container and connect the cs-repository directly to
your database.
```

2023-01-18 16:47 UTC, vprovaggi commented on docs/helm/README.md
> +environments please see the [Security](security.md) section.
```suggestion
## Using the Helm charts

To set your secrets please see the [Security](security.md) section, especially for deployment in sensitive
environments
```

2023-01-18 16:47 UTC, vprovaggi commented on docs/helm/README.md
> +charts](https://github.com/bitnami/charts) and do not configure any logging or
```suggestion
Out of the box we provide a PostgreSQL database via [Bitnami
charts](https://github.com/bitnami/charts) and do not configure any logging or
```

2023-01-20 10:34 UTC, alxgomz approved these changes

2023-01-20 10:34 UTC, alxgomz commented on docs/helm/README.md
> +and configuration for customers who wants to take advantage of Kubernetes
```suggestion
and configuration for customers who want to take advantage of Kubernetes
```

2023-01-20 14:38 UTC, merged