OPSEXP-1931 Create a dedicated workflow for helm unit tests
Alfresco/acs-deployment pull request #862
Opened 2023-01-24 12:06 UTC by slohe1

2023-01-25 10:09 UTC, alxgomz requested changes

2023-01-25 10:09 UTC, alxgomz commented on .github/workflows/helm-community-test.yml
> +name: Helm (Community-unit-test)
The workflow is not community specific. It happened to live in the community workflow before but it actually applies to enterprise as well.
Remove community mentions and rename workflow file

2023-01-25 10:09 UTC, alxgomz commented on .github/workflows/helm-community-test.yml
> +      - pr-*
looks like a legcay stuff... What do you think about getting rid of it?

2023-01-30 09:28 UTC, gionn approved these changes

2023-01-30 16:02 UTC, alxgomz approved these changes

2023-01-30 16:20 UTC, merged