OPSEXP-1932 Added updated file with Admin Console
Alfresco/acs-deployment pull request #878
Opened 2023-02-02 11:53 UTC by upandey123

The new Enterprise trial of ACS (7.3) includes the Admin Console. The diagram ([compose-enterprise.png](https://docs.alfresco.com/content-services/images/compose-enterprise.png)) in the install using Docker containers documentation ([Alfresco Docs - Install using Docker Compose](https://docs.alfresco.com/content-services/latest/install/containers/docker-compose/#deployment-project-in-github) ) needs to be updated to include the Admin Console.

2023-02-02 14:23 UTC, gionn reviewed
LGTM but wait also for alex

2023-02-02 15:55 UTC, alxgomz requested changes
Please also commit the source of the diagram

2023-02-02 15:57 UTC, alxgomz commented
Your style looks neat compared to previous one. Can you also regenerate the other docker-compose diagrams so they look they have the same look & feel?

2023-02-02 16:54 UTC, upandey123 commented
> Please also commit the source of the diagram

Have gone through this document the Detailed Architecture of the workflow.

https://docs.alfresco.com/content-services/latest/develop/software-architecture/#detailed-architecture

2023-02-02 16:59 UTC, upandey123 commented
> Your style looks neat compared to previous one. Can you also regenerate the other docker-compose diagrams so they look they have the same look & feel?

These are the other docker--compose diagrams I have got.

<img width="844" alt="Screenshot 2023-02-02 at 10 27 15 PM" src="https://user-images.githubusercontent.com/112844008/216391262-c173a546-3967-4c46-ab00-918dfbe322f4.png">

<img width="891" alt="Screenshot 2023-02-02 at 10 26 53 PM" src="https://user-images.githubusercontent.com/112844008/216391217-968fab18-4833-4637-b52b-b8e7a4855de9.png">

2023-02-03 05:13 UTC, upandey123 commented
Have created a new task for other diagrams to update and will perform it. If this seems good kindly approve!

2023-02-06 09:27 UTC, alxgomz submitted a review, later dismissed

2023-02-06 09:27 UTC, alxgomz commented on README.md
> +* Go to the `docs/docker-compose/diagrams` folder of the repository and there you will find 2 plantuml source files and 2 diagram files.
```suggestion
* Go to the `docs/docker-compose/diagrams` and/or `docs/helm/diagrams` folders of the repository and there you will find 2 plantuml source files and their PNG diagram files.
```

2023-02-06 09:27 UTC, alxgomz commented on docs/docker-compose/diagrams/docker-compose-enterprise.puml
> +adw --> acs
This one should not be there. Please fix and regenerate

2023-02-06 09:54 UTC, alxgomz approved these changes

2023-02-06 09:59 UTC, merged