OPSEXP-2117 acs-deployment to rely on chart alfresco-connector-msteams
Alfresco/acs-deployment pull request #956
Opened 2023-07-01 17:53 UTC by slohe1

2023-07-03 09:29 UTC, alxgomz reviewed
There is no meaningful test here.
We should try that branch on develop branch of the integration pipeline given it's the only one that can really deploy and configure properly the instances.
Doing that require some communication that we will break develop

2023-07-10 07:19 UTC, gionn requested changes

2023-07-10 07:19 UTC, gionn commented on helm/alfresco-content-services/values.yaml
> -    repository: quay.io/alfresco/alfresco-ms-teams-service
keep it just for reference together with tag

2023-07-14 08:03 UTC, gionn requested changes

2023-07-14 08:03 UTC, gionn commented on helm/alfresco-content-services/7.0.N_values.yaml
> +alfresco-connector-msteams:
document this change in the upgrade md

2023-07-14 13:57 UTC, gionn requested changes

2023-07-14 13:57 UTC, gionn commented on docs/helm/upgrades.md
> +
```suggestion
```

don't see the need of saying it again, the previous paragraph should be enough

2023-07-17 07:07 UTC, gionn approved these changes

2023-07-17 08:57 UTC, merged